name: Build and Deploy to AWS
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to interact with GitHub's OIDC Token endpoint.
      contents: read

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Create .env.local
        working-directory: ./app
        run: |
          touch .env.local
          echo DB_USER=${{ secrets.CI_DB_USER }} >> .env.local
          echo DB_HOSTNAME=${{ secrets.CI_DB_HOSTNAME }} >> .env.local
          echo DB_PASSWORD=${{ secrets.CI_DB_PASSWORD }} >> .env.local
          echo NEXTAUTH_URL=${{ vars.CI_NEXTAUTH_URL }} >> .env.local
          echo NEXTAUTH_SECRET=${{ secrets.CI_NEXTAUTH_SECRET }} >> .env.local
          echo GOOGLE_CLIENT_ID=${{ secrets.CI_GOOGLE_CLIENT_ID }} >> .env.local
          echo GOOGLE_CLIENT_SECRET=${{ secrets.CI_GOOGLE_CLIENT_SECRET }} >> .env.local
          echo AWS_PROFILE=${{ secrets.CI_AWS_PROFILE }} >> .env.local
          echo AWS_S3_BUCKET=${{ secrets.CI_AWS_S3_BUCKET }} >> .env.local
          echo OPENAI_API_KEY=${{ secrets.CI_OPENAI_API_KEY }} >> .env.local


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          # This might only work for dev?
          role-to-assume: arn:aws:iam::258343757818:role/AppDeployRole
          aws-region: us-east-2

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition fargate-node-task-defn --query taskDefinition > task-definition.json

      - name: Build, tag, and push image to Amazon
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: auditre-fargate-app
          IMAGE_TAG: latest
        working-directory: ./app
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> "$GITHUB_OUTPUT"

      - name: Fill in the new image ID in the AWS ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        env:
          IMAGE: ${{ steps.build-image.outputs.IMAGE }}
        with:
          task-definition: task-definition.json
          container-name: nodejs-app-container
          image: "$IMAGE"

      - name: Deploy AWS ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: fargate-node-service
          cluster: fargate-node-cluster
          wait-for-service-stability: true


#  uses: actions/cache@v3
# with:
#   # See here for caching with `yarn` https://github.com/actions/cache/blob/main/examples.md#node---yarn or you can leverage caching with actions/setup-node https://github.com/actions/setup-node
#   path: |
#     ~/.npm
#     ${{ github.workspace }}/.next/cache
#   # Generate a new cache whenever packages or source files change.
#   key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
#   # If source files changed but packages didn't, rebuild from a prior cache.
#   restore-keys: |
#     ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
